### ISSUE TITLE
Option for custom mousemove handler

### ISSUE THREAD

**Issue by birdspider** [IHCantabria/Leaflet.CanvasLayer.Field#1]
I'm not able to do `layer.on('mousemove', somefn)` whereas `layer.on('click', somefn)` works. Is this by design ? Or is there another option.

I want to display the value on hover in a box i.e. below the map.

**Comment by VictorVelarde** [comment]
Hi there @birdspider,
Thank you for your interest and playing with the plugin!

`mousemove` is not implemented yet, but I agree it is quite interesting to add it.
Let me have a look at it and I will include it asap.

**Comment by VictorVelarde** [comment]
Hi again,
I've included the `mousemove` event, and reestructured a bit the class. Please have a look at it.

The plugin is still in early development, so any feedback is welcome!

**Comment by VictorVelarde** [comment]
I suppose everything is fine with this @birdspider, so I'm closing the issue.

**Comment by birdspider** [comment]
ah yes everything is fine :) - sorry that I missed that
