### ISSUE TITLE
Hide/show effect during 1..3 seconds on zooming

### ISSUE THREAD

**Issue by pixime** [IHCantabria/Leaflet.CanvasLayer.Field#11]
Very good work, thanks !

Do you know a workaround in order to avoid the hide/show effect when zooming an image in a Leaflet map ? 

For example, with base Layer, Leaflet increase or decrease the current images and when it gets new images, the old ones are smoothly replaced by the new ones.

**Comment by VictorVelarde** [comment]
Thanks @pixime I'm glad you like it! 

Currently I hide the canvas to avoid showing it in an incorrect position during the movement.  I don't know a better workaround. 

Maybe I could have a look at it, but after fixing the previous 2 open issues.

And pull requests are always welcomed!

**Comment by VictorVelarde** [comment]
@felipem775 I think this issue should be closed
