### ISSUE TITLE
Improving performance with geogiff overlays or get a static ImageOverlay

### ISSUE THREAD

**Issue by h0gar** [IHCantabria/Leaflet.CanvasLayer.Field#13]
I use your tool to load geogiffs (georeferenced images) as overlays.

The issue I have with it is that the tool works by rerendering geogiff overlays after every move. It's slow and it hangs.

I tried modifying it to generate an ImageOverlay instead of a L.CanvasLayer.ScalarField so that it doesn't have to rerender the geogiff overlay after every move. It works.. almost.

The problem I have now is that Leaflet.CanvasLayer.Field renders the image by scanning the layer. So without doing map.fitBounds(bounds) beforehand, it doesn't work. With max bounds -180/180 on the leaflet map, when the geogiff crosses the 180th meridian, it fails to render the image.

Is there a way to render the image with a different technique? So that, from the geogiff data, I can have an image and place it using the corners of the geogiff file. I tried but with not much success.

Here is my function. The function trim removes the transparent pixels around the image. Ideally I would get rid of that and map.fitBounds.
```
getGeoGiffOverlay: function(map, arrayBuffer, options) {
        let geo = this.fromGeoTIFF(arrayBuffer);

        var extent = geo.extent(),
            latlng1 = L.latLng(extent[1], extent[0]),
            latlng2 = L.latLng(extent[3], extent[2]);
        var bounds = L.latLngBounds(latlng1, latlng2);

        map.fitBounds(bounds);

        var canvas = L.DomUtil.create("canvas", "leaflet-layer");
        var size = map.getSize();
        canvas.width = size.x, canvas.height = size.y;

        var context = canvas.getContext("2d");
        context.clearRect(0, 0, canvas.width, canvas.height);

        var width = canvas.width,
            height = canvas.height;
            var img = context.createImageData(width, height);
        var data = img.data;

        var origin = map.getPixelOrigin();

        for (var i = 0, y = 0; y < height; y++) {
            for (var x = 0; x < width; x++) {
                var point = map.containerPointToLayerPoint(L.point(x, y));
                point = point.add(origin);
                var unprojected = map.unproject(point);

                var lng = unprojected.lng;
                var lat = unprojected.lat;
                var color = geo['valueAt'](lng, lat);
                if (null !== color) {
                    color >>>= 0;
                    var B = color & 0xFF,
                        G = (color & 0xFF00) >>> 8,
                        R = (color & 0xFF0000) >>> 16,
                        A = 255 ;

                    data[i] = R, data[i + 1] = G, data[i + 2] = B, data[i + 3] = parseInt(255 * A)
                }
                i += 4
            }
        }

        context.putImageData(img, 0, 0);

        canvas = this.trim(canvas);

        var imageData = canvas.toDataURL('image/png');

        var _latlng1 = {lat: latlng2.lat, lng: latlng1.lng};
        var _latlng2 = {lat: latlng1.lat, lng: latlng2.lng};
        var latLngBounds = L.latLngBounds(_latlng1, _latlng2);
        return L.imageOverlay(imageData, latLngBounds, options);
}
```

**Comment by VictorVelarde** [comment]
Hi @h0gar,

I appreciate your interest in the plugin.

It's true, it currently re-renders after every move. That was a requirement for the first layer I created (the animation with VectorFieldAnim) and the second one. ScalarField, simply inherited the same behaviour.

I agree that a single-render approach such as yours would be far better and I would love to apply it in the long term.

If you just want another geotiff rendering alternative right now maybe you could try with https://github.com/stuartmatthews/leaflet-geotiff, or  http://geoexamples.com/d3-raster-tools-docs/plot/leaflet.html which follow an ImageOverlay approach

Of course, feel free to make a pull-request to this repo if you want to contribute with this improvement.

**Comment by VictorVelarde** [comment]
@felipem775 I think this issue should be closed. I guess a good PR with specs will be welcome, but that it's up to you!
