### ISSUE TITLE
Add support to xllcenter and yllcenter

### ISSUE THREAD

**Issue by santiquetzal** [IHCantabria/Leaflet.CanvasLayer.Field#17]
Hello,

I want to render some ESRI ASCII files provided by spanish government, but they use xllcenter and yllcenter in the definition of the ascii file (instead of xllcorner and yllcorner), but they're not supported by this library yet.

The [definiton of ESRI ASCII Raster Format](http://resources.esri.com/help/9.3/arcgisdesktop/com/gp_toolref/spatial_analyst_tools/esri_ascii_raster_format.htm) specifies that an ESRI file can contains one pair of:
* _XLLCORNER and YLLCORNER_ 
* _XLLCENTER and YLLCENTER_

Geographical files provided in [IGN](http://centrodedescargas.cnig.es/CentroDescargas/index.jsp) (For example in section: Modelos digitales de elevaciones > MDT200 > ...) are formed by XLLCENTER and YLLCENTER.

Thank you in advance.

**Comment by VictorVelarde** [comment]
Thanks for pointing it out. I will try to include it in future releases.

**Comment by VictorVelarde** [comment]
Hi @santiquetzal, 

I have made some changes to the plugin, to allow xllcenter and yllcenter in ASCII Grid files. I know it's been a while since you requested, but maybe it is still useful for you and you can have a look at it.

The update is available in the master, not at npm yet!

**Comment by VictorVelarde** [comment]
This should be working in v1.4.1. 
Feel free to re-open this issue if you have any problem!
