### ISSUE TITLE
Error reading geotiff: Ran off the end of the buffer before finding EOI_CODE

### ISSUE THREAD

**Issue by santiquetzal** [IHCantabria/Leaflet.CanvasLayer.Field#19]
Hello,

I'm trying to display a TIFF file over leaflet.
The tz850.tiff file provided in data directory works perfectly.

I need to display a TIFF file obtained from [http://centrodedescargas.cnig.es](http://centrodedescargas.cnig.es). I tried with several maps, the last one was 'mtn25_epsg25829_0001-2.tiff' (17.9 MB).

 When the line `image.readRasters();` is executed the brower console shows the following error:
```
ran off the end of the buffer before finding EOI_CODE (end on input code)
```

Do you have any idea of what could be causing this error?

Thanks.

Note: If I open the geotiff file with QGIS, it tells me that the file metadata is:
```
Controlador: 
   GDAL provider GTiff GeoTIFF
Descripción del conjunto de datos:
  <folder>/mtn25_epsg25829_0021-4.tif
    AREA_OR_POINT=Area
Banda 1
Banda 2
Banda 3
Dimensiones
    X: 13582 Y: 9373 Bandas: 3
Origen
    552284,4.80741e+06
Tamaño de píxel
    1,-1
Valor sin datos
    *No se ha establecido el valor sin datos (NoDataValue)* 
Tipo de datos
    Byte - Entero natural de 8 bits
Vistas generales de pirámides
Sistema de referencia espacial de la capa
    +proj=utm +zone=29 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
Extensión de la capa (proyección de la fuente original de la capa)
    552283.8551724179415032,4798033.7175342505797744 : 
    565865.8551724179415032,4807406.7175342505797744
Banda 1
    Número de banda 1
    No hay estadísticas
Todavía no se han recogido estadísticas
Banda 2
    Número de banda 2
    No hay estadísticas
Banda 3
    Número de banda 3
```

**Comment by VictorVelarde** [comment]
Hi Santiago,

That warning is thrown by the underlying `geotiff.js` library, and it manifests when using some LZW raster files. But that doesn't necessary breaks the rendering process (see for example the very same message in this working [example](https://ihcantabria.github.io/Leaflet.CanvasLayer.Field/example_ScalarField_Geotiff_Bigger.html).

You should reproject your dataset with QGIS and try again. The only supported **EPSG is 4326** (lon-lat WGS84). Let's see if that fixes the problem.

**Comment by santiquetzal** [comment]
I reprojected the file with QGIS, I tried 2 methods, but the raster is never shown on the map.

I used these methods:
* Via: Raster > Conversion > Translate
     I filled the output file name and target EPSG (To EPSG:4326).
    The new file has 373 MB (the original was 17MB)
* Via: Processing > Toolbox > GDAL > Conversion > Translate. 
    I filled output projection (EPSG:4326) and target file name.
    The new file has 28 MB.

I will try to use another tool to make the conversion. 

I put here the metadata info, if you see anything strange I will apreciate your help.

In the file metadata (original and converted) the Layer extension is:
`578723.7496583280153573,4844572.9432823723182082 : 592250.7496583280153573,4853999.9432823723182082`
But in you .tif file (and others I downloaded from other gis repository) the values are lat/lng friendly:
`44.0963439710014029,33.0161412438675583 : 44.6962375710014044,33.6161736438675618`

Maybe the problem is that the coordinates are not converted.


Metadata: (Copied from QGIS)
* [original.metadata.txt](https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/files/1517772/original.metadata.txt)
* [test1.txt](https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/files/1517774/test1.txt)
* [test2.txt](https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/files/1517775/test2.txt)

Thank you in advance.

**Comment by VictorVelarde** [comment]
Hi Santiago,

I think the conversion to EPSG:4326 is wrong. 

**test2.txt** indicates the units are wrong (extension and units not corresponding with expected, much lower values, corresponding to decimal degrees).

Have a look at https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/issues/9 for a quite similar issue.

I think you should try with *gdal_warp*, gdal_translate just converts raster data between different formats (eg. from ASCII grid to GeoTIFF), but it doesn't reproject.

Validate metadata and units outside the plugin, in QGIS, and once it looks fine, try again.

**Comment by santiquetzal** [comment]
I will try to convert the file using gdal_warp, but I'm pretty sure the problem are with the units in the converted file are wrong.

Thank you for your advice!

Note: You can close the issue because is not related with you library.

**Comment by VictorVelarde** [comment]
OK. Feel free to open it again in the future.
