### ISSUE TITLE
0 values 

### ISSUE THREAD

**Issue by birdspider** [IHCantabria/Leaflet.CanvasLayer.Field#2]
I'm not 100% sure but it seems that geotiff with i.e. fileDirectory.GDAL_NODATA=-1 and values [0,306]  my 0 values (int in this case) are not rendered or interpreted as null/nodata. 

Further I tested the color function, it never gets the value 0; 
In fact I happen to have a geotiff with only -1=nodata and 0 as data. The colorfunction is NOT called  a single time.

I checked the existence of GDAL_NODATA in the js and it is there. Any ideas?

EDIT:

this hack worked around it

```
 zs = Array.from(zs).map(function(z) {
  return z === noData ? null : (z === 0 ? 1e-10 : z);
 });
```

**Comment by VictorVelarde** [comment]
Hi again,

I would like to have a look at that geotiff. 

I have prepared this codepen as a template for plugin issues:
https://codepen.io/VictorVelarde/pen/ZKJWMb

Could you please provide a working example with it?

I really appreciate your feedback!

**Comment by VictorVelarde** [comment]
Hi @birdspider 
I have prepared a quick example with a similar raster and I have found a bug (indeed 2 little errors), regarding to the consideration of 0 as a 'false' value. On one hand, that blocked the rendering at all for this value. On the other hand, it was also breaking 'onmousemove', for the same reason. 

Can you please confirm that d8bdc10 fixes all issues with your dataset? 

You can use this http://codepen.io/VictorVelarde/pen/KmByeq if it helps you.

Thanks!

**Comment by birdspider** [comment]
hello, 

it seems to be fixed - thx

**Comment by VictorVelarde** [comment]
Great! 
Let me know if you find any other problem
