### ISSUE TITLE
Default cursor is changed by the layer

### ISSUE THREAD

**Issue by robertbridgart** [IHCantabria/Leaflet.CanvasLayer.Field#20]
When I include a layer of this type in Leaflet, I lose the default cursor (grab) and the grabbing one for panning. It seems the layer changes the cursor for the entire layer stack to a pointer.

How can I include your layer and still retain default cursor behavior when not specifically interacting with your layer (i.e. mouseover)?

Thanks

**Comment by VictorVelarde** [comment]
Hi @robertbridgart 

Thank you for your interest in the plugin. It is true, right now the plugin changes the cursor by default, but you can easily override that behaviour with `mouseMoveCursor`, like this:

```
    const options = { mouseMoveCursor: null }; 
    const layer = L.canvasLayer.scalarField(f, options);
```

Here it is a working example: https://codepen.io/VictorVelarde/pen/gvRQpp
Let me know if this fits your use case. 

I will soon prepare a little doc to document the API, revealing this kind of options.

**Comment by robertbridgart** [comment]
That resolved my issue. Thanks for the fast reply and keep up the good work.
