### ISSUE TITLE
Support Geotiffs that use geotransform (w/o modelpixelscale or tiepoints)

### ISSUE THREAD

**Issue by beihl** [IHCantabria/Leaflet.CanvasLayer.Field#21]
Loading geotiffs assumes they have tie points and model pixel scale.
But geotiffs can alternately use Model Transform.

Something like this in `ScalarField.multipleFromGeoTIFF` handles both cases:

`      

        let fileDirectory = image.getFileDirectory();
        let xScale = 0, yScale = 0;
        let tiepoint = {i:1,j:1,k:1,x:0,y:0,z:0};
        if( image.hasOwnProperty('tiepoint'))
            tiepoint = image.getTiePoints()[0];
        if (fileDirectory.hasOwnProperty('ModelPixelScale'))
            [xScale, yScale] = fileDirectory.ModelPixelScale;
        else
            if(fileDirectory.hasOwnProperty('ModelTransformation')) {
                let transform = fileDirectory.ModelTransformation;
                xScale = transform[0];
                yScale = -transform[5];
            }
`

**Comment by VictorVelarde** [comment]
Hi @beihl

Thank you very much for your code!

I have seen your ongoing conversation at https://github.com/constantinius/geotiff.js/issues/40 and I will try to use this approach in an integration with a future release of `geotiff.js`.

I'll leave this open in the meantime

**Comment by beihl** [comment]
Oops, need to add tiepoints from transform

    let fileDirectory = image.getFileDirectory();
    let xScale = 0, yScale = 0;
    let tiepoint = {i:1,j:1,k:1,x:0,y:0,z:0};
    if( image.hasOwnProperty('tiepoint'))
        tiepoint = image.getTiePoints()[0];
    if (fileDirectory.hasOwnProperty('ModelPixelScale'))
        [xScale, yScale] = fileDirectory.ModelPixelScale;
    else
        if(fileDirectory.hasOwnProperty('ModelTransformation')) {
            let transform = fileDirectory.ModelTransformation;
            xScale = transform[0];
            yScale = -transform[5];
            tiepoint.x = transform[3];
            tiepoint.y = transform[7];
        }

**Comment by VictorVelarde** [comment]
Thx for your contribution @beihl

**Comment by VictorVelarde** [comment]
I made a quick test with your code (using https://ihcantabria.github.io/Leaflet.CanvasLayer.Field/data/tz850.tiff). It might be my fault, but it was bad positioned, so I didn't integrate it for the moment

**Comment by VictorVelarde** [comment]
Hi @beihl I have just noticed you're forking the project
Thanks so much for your interest!

**Comment by VictorVelarde** [comment]
@felipem775 I think this issue should be closed. I guess a good PR with specs will be welcome, but that it's up to you!

**Comment by farzinghanbari** [comment]
I believe the problems were the negative sign of yScale, the initial values of i, j, and k in tiepoint, and checking for tiepoint property of image instead of checking for ModelPoint property of fileDirectory. The code should change to:

```javascript
let fileDirectory = image.getFileDirectory();
let xScale = 0, yScale = 0;
let tiepoint = {i:0,j:0,k:0,x:0,y:0,z:0};
        
if(fileDirectory.hasOwnProperty('ModelTiepoint')){
    tiepoint = image.getTiePoints()[0];
}
if (fileDirectory.hasOwnProperty('ModelPixelScale')) {
    [xScale, yScale] = fileDirectory.ModelPixelScale;
} else {
    if(fileDirectory.hasOwnProperty('ModelTransformation')) {
        let transform = fileDirectory.ModelTransformation;
        xScale = transform[0];
        yScale = transform[5];
        tiepoint.x = transform[3];
        tiepoint.y = transform[7];
    }
}
```

This solved my problem.
