### ISSUE TITLE
More dynamic color bar?

### ISSUE THREAD

**Issue by mmirhi** [IHCantabria/Leaflet.CanvasLayer.Field#23]
Hi

Thank you so much for this great plugin. I created a color bar similar to the one in the example demo: https://ihcantabria.github.io/Leaflet.CanvasLayer.Field/example_VectorFieldAnim_ColorBar.html

Is it possible to make the color bar more dynamic? For example, I want to give the user the option to set the limits of the color scheme. Let's say I am plotting a temperature field and the data ranges between 0 and 20 (where 0 is blue and 20 is red). As of now, my colorbar presents the same scheme, but what if the user wants that color scale between 5 and 15 (in this case, 0 to 5 would be blue and 15 to 20 would be red, and 5 to 15 would be the same full color scale like the data.). I am new to JS so I am not sure how to work this. 

Any help is appreciated.

**Comment by felipem775** [comment]
Hi @mmirhi ,

The colorbar uses [chroma.js](http://gka.github.io/chroma.js/).

The colors are distributed in regular sections. So you can use 5 colors (values: 0, 5, 10, 15, 20).  
If you want to show blue for 0 to 5 and red for 15 to 20, you must repeat the colors and calculate the interpolated colors between 5 and 15:

```javascript
f = chroma.scale(['blue', 'red']).domain([5,15])
f(10).hex() // #800080
```

```javascript
// 0 blue, 5 blue, 10 interpolate blue/red, 15 red, 20 red
var scale = chroma.scale(['blue','blue','#800080', 'red', 'red']).domain([0, 20]),
```

**Comment by mmirhi** [comment]
Thanks for the quick reply. I understand what you explained, but what if I want to give the user the option to choose these limits. I mean on the colorbar itself, I want an option where the viewer can enter the numbers (5 and 15), so they can control the color scheme according to what they like to see. Is that doable? Thanks a bunch :)

**Comment by felipem775** [comment]
I think you want something like this [example](http://gka.github.io/palettes/)
You can replace the scalebar in the client side. 
If you have a problem with the code, do not hesitate to paste it here.
