### ISSUE TITLE
Transparent color for 0 values.

### ISSUE THREAD

**Issue by nzahasan** [IHCantabria/Leaflet.CanvasLayer.Field#24]
How can I use transparent color for 0 values?

**Comment by nzahasan** [comment]
got it `chroma.scale(['rgba(0,0,0,0)','rgba(255,255,255,1)']).domain(s.range)`

**Comment by felipem775** [comment]
Hi @nzahasan 
I have been doing some tests and they didn't work. Maybe chroma.js doesn't support alpha in scale.
They have opened an issue https://github.com/gka/chroma.js/issues/178

**Comment by VictorVelarde** [comment]
@nzahasan maybe you could try with a filter, excluding all values <= 0 (if that fits your requirements). Have a look at: https://ihcantabria.github.io/Leaflet.CanvasLayer.Field/example_ScalarField_Filter.html

**Comment by nzahasan** [comment]
@VictorVelarde thanks that's what I was looking for.

**Comment by VictorVelarde** [comment]
Great, @nzahasan then this issue should be close! @felipem775

**Comment by gka** [comment]
the RRGGBBAA hex code also works

```js
chroma.scale(["#00000000", "#ffffffff"])
```
