### ISSUE TITLE
Scalar field blur

### ISSUE THREAD

**Issue by mmirhi** [IHCantabria/Leaflet.CanvasLayer.Field#25]
Hi

I have two questions.

1- I have been working on visualizing ocean temperature distribution using this awesome function. There is an obvious blur in my field (screenshot attached), and the blur is unrelated to the color palette because I tried different ones. A friend of mine viewed the map on another server with a slower refresh rate and the map got much better and more contours were shown. Is there anything I can do about this? Where in the code are the blur and the refresh rate handled?

2- I want to view the change in this temperature profile with time, using the time slider of Leaflet.timedimension, but I am not sure how to link the layers produced from the ASCII files to their corresponding times. Would you know of a successful example code that combines both functions?

Thank you so much
![temp](https://user-images.githubusercontent.com/40373221/43347230-8d8338e6-91c2-11e8-98cc-9f9f753584cf.png)

**Comment by CorbinFoucart** [comment]
To @mmirhi's point 1: 

1 - It seems that this is built on top of a contourf type plot, but then blends the result. If the same html is viewed through a graphics forwarding program at a lower refresh rate, the contour lines become visible. 

Where in the source code is this "blurring" / interpolation done, and is it simple to recover the filled contour plot as below?

![0](https://user-images.githubusercontent.com/4095293/43403083-38406f1c-93e2-11e8-8d2e-b49b64fecf3c.png)

**Comment by CorbinFoucart** [comment]
Another followup question: what is the library that's doing the actual rendering of the image?

Thank you.

**Comment by VictorVelarde** [comment]
The library itself is rendering to the canvas (see https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/blob/master/src/layer/L.CanvasLayer.ScalarField.js#L71 for simple raster rendering)

The interpolation is bilinear (https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/blob/master/src/Field.js#L209). 

There is an example on how to activate / deactivate it, here: https://ihcantabria.github.io/Leaflet.CanvasLayer.Field/example_ScalarField_Interpolation.html

**Comment by CorbinFoucart** [comment]
I see, thanks; in that case, it is strange that the contour lines become visible when viewing the plot at a lower refresh rate through the graphics forwarding software, that the contour lines become visible... any idea why this might be the case?

**Comment by VictorVelarde** [comment]
It might be that, but I have no experience on graphics forwarding... What engine are you using?

**Comment by CorbinFoucart** [comment]
TeamViewer. I'm almost sure this is the case.

**Comment by VictorVelarde** [comment]
@mmirhi regarding to the TimeDimension integration, there are some developments at IHCantabria (not as a plugin, not as open source, but definitely working...)

And there are some public projects using them, like http://dss.trlplus.com

**Comment by VictorVelarde** [comment]
@mmirhi regarding to the TimeDimension integration, there are some developments at IHCantabria (not as a plugin, not as open source, but definitely working...)

And there are some public projects using them, like http://dss.trlplus.com.

And if you want 'crispier' limits in your contours, then maybe this example could be useful: https://ihcantabria.github.io/Leaflet.CanvasLayer.Field/example_ScalarField_Styles.html

The idea is that you can completely customize your palette, thx to chromajs flexibility, specifying the colors and step values, the number of classes...

**Comment by VictorVelarde** [comment]
Try with these suggestions and, if successful, please close the issue (@felipem775)
