### ISSUE TITLE
slow zoom in and out

### ISSUE THREAD

**Issue by nzahasan** [IHCantabria/Leaflet.CanvasLayer.Field#26]
I have noticed that at zoom the scaler drawing is pretty slow. I am pretty sure the reason is that `_drawImage` is being called multiple time(3 times) at each zoom event one is by movestart another is by moveend and I cant find out which one is calling third time. Is there a fix for this.

**Comment by nzahasan** [comment]
found out the 3rd call zoom event fires move event too.

**Comment by joaquinperaza** [comment]
Could you find any solution for this? I moved to this library from https://github.com/stuartmatthews/leaflet-geotiff and now I am facing that problem, it seems like the image drawing methods freezes the front end when browsing the map
