### ISSUE TITLE
CellSize Issue

### ISSUE THREAD

**Issue by nzahasan** [IHCantabria/Leaflet.CanvasLayer.Field#29]
https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/blob/ba1057bfc3f02a24c54e3b72b4e51753f3202929/src/ScalarField.js#L65

I think it should be `cellSize/2`

**Comment by VictorVelarde** [comment]
It looks so, and obviously the same with YLLCENTER

**Comment by VictorVelarde** [comment]
Maybe @felipem775 could fix master with this. It would be great!

**Comment by Pedrazl** [comment]
Fixed:
https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/pull/38
