### ISSUE TITLE
IE Support - `new.target`

### ISSUE THREAD

**Issue by birdspider** [IHCantabria/Leaflet.CanvasLayer.Field#3]
Hi, 

it's me again ! :) 

in [src/Field.js#L10](https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/blob/b2329c2a11004b2399ddefe7258ab12caf7c6e63/src/Field.js#L10) there is this new and fancy
syntax `new.target`, which is not polyfillable and survives into dist.

So, according to the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target) neither Safari nor IE (Edge is not explicilty mentioned) support it.

Any idea how to solve this. Differently phrased: do you plan to support IE.X and or Edge.

Same problem somewhere else: https://github.com/PeculiarVentures/ASN1.js/issues/19

**Comment by VictorVelarde** [comment]
Supporting IE is not a priority.

Nevertheless, if deleting this `new.target` improves browser support, I have no problem deleting it, cause it doesn't create any issue.
