### ISSUE TITLE
Not a valid ASCIIGrid Header: TypeError: e[1] is undefined

### ISSUE THREAD

**Issue by alirezamdv** [IHCantabria/Leaflet.CanvasLayer.Field#31]
Hi,
i use leaflet.canvaslayer.field v1.4.1 .i get this error, didn't find any related answer in google.
my ascii grid files are .grd files and  i can open it with qgis without problem.
thank you

Error: Not a valid ASCIIGrid Header: TypeError: e[1] is undefined ScalarField.js:75:18
value
ScalarField.js:75:18
value
ScalarField.js:18:21
 
grid files with gdal : 
Driver: GSBG/Golden Software Binary Grid (.grd)
Size is 10784, 23000
Coordinate System is `'
Origin = (-80.837503782394649,-17.000503265369584)
Pixel Size = (0.001000000006202,-0.001000000022548)
Corner Coordinates:
Upper Left  ( -80.8375038, -17.0005033) 
Lower Left  ( -80.8375038, -40.0005038) 
Upper Right ( -70.0535037, -17.0005033) 
Lower Right ( -70.0535037, -40.0005038) 
Center      ( -75.4455037, -28.5005035) 
Band 1 Block=10784x1 Type=Float32, ColorInterp=Undefined
  Min=0.000 Max=28.780 
  NoData Value=1.70141000918782799e+38

**Comment by VictorVelarde** [comment]
The plugin doesn't allow binary grid files, just plain ascii files. Export as Ascii Grid first
