### ISSUE TITLE
Publishing the plugin to npm

### ISSUE THREAD

**Issue by konstantinkobs** [IHCantabria/Leaflet.CanvasLayer.Field#4]
It would be really helpful to publish this plugin to npm. Currently I am working on a project that could benefit from this plugin but all the other dependencies I am using can be installed via npm. It would be very convenient if you could add this plugin to npm.

Thank you in advance.

**Comment by VictorVelarde** [comment]
Hi @konstantinkobs 
Thank you for your interest in the plugin. I will publish it to npm as soon as I have solved some little issues (hopefully 1-2 weeks). Is that fine for you?

**Comment by konstantinkobs** [comment]
Sounds great! Thank you! Until then I will just download the script. 😄

**Comment by VictorVelarde** [comment]
Hi again @konstantinkobs
I have just released v1.0.0 , available at [npm](https://www.npmjs.com/package/leaflet-canvaslayer-field)
Let me know if you have any problem or feedback!
