### ISSUE TITLE
map pane

### ISSUE THREAD

**Issue by njadid** [IHCantabria/Leaflet.CanvasLayer.Field#46]
Thanks for your extension! It is really helpful!
Just a suggestion: 
To be able to reorder the layers in leaflet,
I have modified lines 1075-1085 so that layer could be added to user-defined "map pane" by passing it in the options. I am newbie in Javascript, so you can edit it better.
`
, onAdd: function (t) {
            this._map = t, this._canvas = L.DomUtil.create("canvas", "leaflet-layer"), this.tiles = {};
            var e = this._map.getSize();
            this._canvas.width = e.x, this._canvas.height = e.y;
            var n = this._map.options.zoomAnimation && L.Browser.any3d;
            L.DomUtil.addClass(this._canvas, "leaflet-zoom-" + (n ? "animated" : "hide")), _this.options.hasOwnProperty('pane') ? t._panes[this.options.pane].appendChild(this._canvas): t._panes.overlayPane.appendChild(this._canvas)_, t.on(this.getEvents(), this);
            var i = this._delegate || this;
            i.onLayerDidMount && i.onLayerDidMount(), this.needRedraw()
        }, onRemove: function (t) {
            var e = this._delegate || this;
            e.onLayerWillUnmount && e.onLayerWillUnmount(), _this.options.hasOwnProperty('pane') ? t.getPanes()[this.options.pane].removeChild(this._canvas): t._panes.overlayPane.removeChild(this._canvas)_, t.off(this.getEvents(), this), this._canvas = null
        }`

**Comment by Pedrazl** [comment]
Thanks @njadid . Maybe you could make a PR with this addition?

**Comment by adlzanchetta** [comment]
The solution proposed was useful to me.

As this issue seem to be left open for a while, I took the freedom to make the PR with the adaptations for the current implementation of the library (line numbers and variable names have some mismatches).

Thanks @Pedrazl for the project and thanks @njadid for the solution proposed.

**Comment by Pedrazl** [comment]
Merged  on #59 👍
