### ISSUE TITLE
can I add transparency to the background of colorbar? 

### ISSUE THREAD

**Issue by KeqinWu-NOAA** [IHCantabria/Leaflet.CanvasLayer.Field#52]
I tried to read and edit the code  "L.Control.ColorBar.js" by adding "opacity: 0.5" to 'div', nothing is changed. This lead me to another questions, how can I edit on the code?
I put the whole Leaflet.Canvaslayer.Field directory locally.

**Comment by Pedrazl** [comment]
Hi @KeqinWu-NOAA ,
you don't need to change the code. The ColorBar object has properties to define several options, 'background' is one of them. 
When you create the color bar, make sure you send the options you like to the constructor.
`
                var bar = L.control.colorBar(scale, range, {                    
                    background: 'transparent',                   
                }).addTo(map);`
