### ISSUE TITLE
New player controler

### ISSUE THREAD

**Issue by adlzanchetta** [IHCantabria/Leaflet.CanvasLayer.Field#60]
Hi,
I am developing a new controller for playing/pausing multi-layer geotiffs. The initial motivation is to display "animated" precipitation products, but it certainly can be used for other purposes. I would like to ask what you all think about including this controller to the main project repository - i.e.: does it fit the scope of the project? could it be useful?

It can be accessed [here](https://adlzanchetta.github.io/Leaflet.CanvasLayer.Field/example_LayersPlayer.html) (takes a few seconds to load - probably I should use a smaller tiff file).

If you find it is considered useful and of general interest, I would be glad to PR it when I have it in a more stable and customizable state (and would also include a nice gif example for the main README.md).

_PS: I am just starting to contribute to open source projects. I apologize if this (opening an issue) is not the appropriate way to suggest new features._

**Comment by Pedrazl** [comment]
Hi @adlzanchetta ,
this contribution would be great! 
For this type of time control, internally we use the excelent TimeDimension plugin created by SOCIB: https://github.com/socib/Leaflet.TimeDimension, have a look, maybe you can find interesting examples.
Anyway, feel free to PR your control and we will integrate it in our plugin. 
Thank you!

**Comment by adlzanchetta** [comment]
@Pedrazl ,
Thank you for talking about the TimeDimension plugin. I was not aware of it.
Indeed the TimeDimension looks great and is in a way more mature state than the controller I am bringing in. I need to explore it better.
Maybe we could include an example with its usage as part of the docs. Or maybe it would include an external dependency that start exceeding the scope of the project...?
Anyway, I just performed the PR with the player controller that can be used as a "bulti-in, example included" alternative to the TimeDimension one.

**Comment by Pedrazl** [comment]
Perfect! I'll merge the PR next week, thanks. 
About the integration of TimeDimension examples, definitely we`ll do in the future.

**Comment by rmarzocchi84** [comment]
I see the PR but it is not merged: https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/pull/61

I am interested using the player because I test it with using https://github.com/Eclipse1979/leaflet-slider but it doesn't work (issue https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/issues/41)

Concerning TimeDimension it is possible to use with Leaflet.CanvasLayer.Field? I only see example with time WMS

**Comment by adlzanchetta** [comment]
@rmarzocchi84
If you find issues using the player, please let me know.

**Comment by Pedrazl** [comment]
Merged today :)
