### ISSUE TITLE
Proposal for a contribution

### ISSUE THREAD

**Issue by claustres** [IHCantabria/Leaflet.CanvasLayer.Field#7]
Dear all, I've started an effort to create a generic Open Source platform on the weather forecast data topic (https://github.com/weacast) and discovered your work. Weacast is a work in progress but I start having a running base, you have some information here https://weacast.gitbooks.io/weacast-docs/.

I started testing your scalar layer for integration and already opened https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/pull/6,  I wonder if you were interested in collaborating to improve your library for Weacast (I found some performance issues) ?

Sorry using the issue tracker for this but didn't know how to contact you, let me know any other prefered way to contact you.

Thanks in advance for your return.

**Comment by claustres** [comment]
Just to let you know I already started working on the performance issue for the scalar field layer. For now you perform interpolation manually each time the layer has to be drawn, which is slow, especially if you have large data sets like I have. So my idea is the following:

1. create an image on `setData()` matching the underlying field values
2. let the browser display it at the right position/scale on `drawLayer()`

Like this the browser makes the interpolation for us, possibly using hardware acceleration. I have something that almost work, jumping from 5/6s on my test data to instant. There is still a bug to fix: a small offset in Y, don't know yet why. If you'd like to have a look before I create a PR : https://github.com/weacast/Leaflet.CanvasLayer.Field/commits/optimized-interpolation

Let me know if you find the bug before me !

**Comment by claustres** [comment]
I wonder if the problem is that the canvas scales the image from the topleft corner and not from the center so stretching it not correctly...

**Comment by VictorVelarde** [comment]
Hi again @claustres 

I have just noticed the displacement when applying interpolation, and, yes it seems to be a 'half-pixel' problem. Let's see if we can find that nasty bug.

On the other hand, improving the performance is a great contribution, so thank you again for your interest.

**Comment by claustres** [comment]
Not sure if it will work, I now wonder if the problem is not the projection distortion. Indeed although pixels of the grid are squares in lat/lon they are not anymore on the screen, the distortion actually depends on the latitude so the sole solution should be what you have done previously by interpolating manually depending on the location of the pixels but I am afraid it is quite limited to small data set due to performance overhead, I will try to investigate a little more but not so convinced it was a good idea :-(

**Comment by claustres** [comment]
I found this project https://github.com/publiclab/Leaflet.DistortableImage/blob/master/src/DistortableImageOverlay.js#L126 where it seems they solved the problem but I have to do some maths...

**Comment by claustres** [comment]
Will you release the version with interpolation fixed meanwhile ? Thanks for your return

**Comment by VictorVelarde** [comment]
Hi @claustres 
Yes, I will release a 1.0.2 today. 

I could not have a look at your work. Right now I'm developing another leaflet plugin, an extension to allow the use of ScalarField and VectorFieldAnim from an OGC-WCS server, with the use of TimeDimension (hopefully to be released soon).

Thanks to you!

**Comment by claustres** [comment]
I've done something like this (although not using WCS) that might help you: https://weacast.gitbooks.io/weacast-docs/api/LAYERS.html

**Comment by VictorVelarde** [comment]
Let's close this and leave it as a reference, collaborating on every specific issue
